afind_formation/urls.py
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formations.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

formations/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('a-propos/', views.about, name='about'),
    path('formations/', views.formations, name='formations'),
    path('formation/<int:pk>', views.formation_detail, name='formation'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('politique-de-confidentialite/', views.privacy_policy, name='privacy_policy'),
    path('conditions-generales-d-utilisation/', views.terms_of_service, name='terms_of_service'),
]

formations/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


class Formation(models.Model):
    title = models.CharField(max_length=200)
    session = models.CharField(max_length=200, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='formations/images/')
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)
    discount = models.IntegerField(default=0, null=True, validators=[MinValueValidator(0), MaxValueValidator(100)], help_text="Enter a discount percentage between 0 and 100")
    date = models.DateField(default=timezone.now, null=True)
    duration = models.CharField(max_length=100, null=True)
    instructor = models.CharField(max_length=560, default='', blank=True)
    department = models.CharField(max_length=255)
    places_left = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    place = models.CharField(max_length=255, default='')
    map_iframe = models.TextField(max_length=800, blank=True, null=True, help_text="iframe of the location on the map")
    status = models.BooleanField(default=True)
    
    class Meta:
        unique_together = [['title', 'session']]

    @property
    def discounted_price(self):
        return self.price - (self.price * self.discount / 100)
    
    def __str__(self):
        return self.title


class FormationImage(models.Model):
    formation = models.ForeignKey(Formation, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='formations/images/formation_%Y/')
    def __str__(self):
        return f"Image for {self.formation.title}"


class Enrollment(models.Model):
    # enrollment_id = models.AutoField(primary_key=True)
    formation = models.ForeignKey(Formation, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, null=True, default='')  
    region = models.TextField(blank=True, null=True) 
    specialty = models.CharField(max_length=255, default='', null=True)
    source = models.CharField(max_length=255, default='Manual', choices=[('Manual', 'Manual'), ('Facebook', 'Facebook'), ('Website', 'Website')], editable=False)
    status = models.CharField(max_length=255, default='Pending', choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')])
    enrollment_date = models.DateField(default=timezone.now, null=True)

    class Meta:
        unique_together = [['formation', 'phone']]

    @property
    def formation_title_session(self):
        return f"{self.formation.title} | {self.formation.session}"
    
    def __str__(self):
        return f"{self.full_name}"
    

class ContactMessage(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.full_name} - {self.email}"


class SiteContent(models.Model):
    CONTENT_TYPE_CHOICES = [
        ('privacy_policy', 'Privacy Policy'),
        ('terms_of_service', 'Terms of Service'),
        ('faq', 'FAQ'),
    ]

    type = models.CharField(max_length=20, choices=CONTENT_TYPE_CHOICES, unique=True)
    title = models.CharField(max_length=200)
    content = models.TextField(help_text="Content of the site section")

    def __str__(self):
        return self.get_type_display()


class SiteSettings(models.Model):
    SETTING_NAME_CHOICES = [
        ('EMAIL_RECEIVER', 'EMAIL RECEIVER'),
        ('EMAIL_HOST_PASSWORD', 'EMAIL HOST PASSWORD'),
        ('EMAIL_HOST_USER', 'EMAIL HOST USER'),
    ]
    setting_name = models.CharField(max_length=100, choices=SETTING_NAME_CHOICES, unique=True)
    setting_value = models.TextField(blank=True)

    def __str__(self):
        return self.setting_name

formations/forms.py
from django import forms
from .models import FormationImage


class FormationImageForm(forms.ModelForm):
    class Meta:
        model = FormationImage
        fields = ['image']
        

class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

formations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q 
from .models import Formation, Enrollment, FormationImage, ContactMessage, SiteContent, SiteSettings

def send_custom_email(subject, message, email):
    # Fetch settings from the database
    try:
        email_settings = SiteSettings.objects.get(setting_name='EMAIL_HOST_USER')
        email_password_settings = SiteSettings.objects.get(setting_name='EMAIL_HOST_PASSWORD')
        email_receiver_settings = SiteSettings.objects.get(setting_name='EMAIL_RECEIVER')
        
        # Override the settings
        settings.EMAIL_HOST_USER = email_settings.setting_value
        settings.EMAIL_HOST_PASSWORD = email_password_settings.setting_value
        # Send the email
        send_mail(
            subject,
            message,
            email,
            [email_receiver_settings.setting_value],
        )
    except SiteSettings.DoesNotExist:
        # Handle case where the settings are not found
        pass


def home(request):
    query = request.GET.get('q') 
    if query:
        formations = Formation.objects.filter(
            Q(title__icontains=query) | 
            Q(instructor__icontains=query) |
            Q(department__icontains=query) |
            Q(place__icontains=query)
        )
    else:
        formations = Formation.objects.filter(status=True)

    content = {
        'formations': formations,
    }
    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        # Save message to database
        ContactMessage.objects.create(
            full_name=full_name,
            email=email,
            subject=subject,
            message=message,
        )
        
        # Send email
        send_custom_email(
            subject,
            message,
            email,
        )
        
        messages.success(request, 'Your message has been sent successfully!')
        return redirect('/#contact')
    return render(request, 'index.html', content)


def formations(request):
    query = request.GET.get('q') 
    if query:
        formations = Formation.objects.filter(
            Q(title__icontains=query) | 
            Q(instructor__icontains=query) |
            Q(department__icontains=query) |
            Q(place__icontains=query)
        )
    else:
        formations = Formation.objects.filter(status=True)
        
    content = {
        'formations': formations,
    }
    return render(request, 'formations.html', content)
    

def formation_detail(request, pk):
    formation = get_object_or_404(Formation, id=pk)
    formation_images = FormationImage.objects.filter(formation=pk)
    formations = Formation.objects.filter(status=True)[:4]
    content = {
        'formation': formation,
        'formation_images': formation_images,
        'formations' : formations
    }
    if request.method == 'POST':
        formation_id = formation.id
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        region = request.POST.get('region')
        specialty = request.POST.get('specialty')
        
        enrollment_date = timezone.now()
        
        # Check if the user is already enrolled
        if Enrollment.objects.filter(formation_id=formation_id, phone=phone).exists():
            messages.error(request, 'You are already enrolled in this formation.')
        else:
            # Save the enrollment data to the database
            Enrollment.objects.create(
                formation_id=formation_id,
                full_name=full_name,
                email=email,
                phone=phone,
                region=region,
                specialty=specialty,
                source = 'Website',
                enrollment_date=enrollment_date
            )
            # formation.places_left -= 1
            # formation.save()
            try:
                # Send email
                send_custom_email(
                    f'{full_name} enrolled in {formation.title} formation',
                    f'{full_name} enrolled in {formation.title} formation by {email}',
                    email,
                )
            except:
                pass
                
            messages.success(request, 'Your form has been submitted successfully!')
            # return redirect('/')
    return render(request, 'formation_detail.html', content)


def about(request):
    content = {}
    return render(request, 'about.html', content)
    

def contact(request):
    content = {}
    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        # Save message to database
        ContactMessage.objects.create(
            full_name=full_name,
            email=email,
            subject=subject,
            message=message,
        )
        
        # Send email
        send_mail(
            subject,
            message,
            email,
            ['seyfeddine.tlm@gmail.com'],  # Replace with your email
        )
        
        messages.success(request, 'Your message has been sent successfully!')
        return redirect('contact')
    
    return render(request, 'contact.html', content)


def faq(request):
    # faqs = SiteContent.objects.filter(type='faq')
    content = {
        'faq': get_object_or_404(SiteContent, type='faq')
    }
    return render(request, 'faq.html', content)
    

def privacy_policy(request):
    content = {
        'policy': get_object_or_404(SiteContent, type='privacy_policy')
    }
    return render(request, 'politique-de-confidentialite.html', content)
    

def terms_of_service(request):
    content = {
        'terms': get_object_or_404(SiteContent, type='terms_of_service')
    }
    return render(request, 'conditions-generales-d-utilisation.html', content)
    

formations/templates/about.html
{% extends "base.html" %}
{% block title %}AFIND Formation{% endblock %}
{% block content %}
    <!--===== HOME =====-->
    {% include "home.html" %}
    <!--===== ABOUT =====-->
    {% include "about_section.html" %}
{% endblock %}

formations/templates/about_section.html
<section class="about section" id="about">
    <h2 class="section-title">À propos du <span class="subtitle">Groupe AFIND</span></h2>
    <div class="container">
        <p class="text">
            AFIND Formation, Centre de Coaching et de Perfectionnement dans le Médical destiné aux professionnels de la Santé.
            <br>
            Le centre AFIND FORMATION, Pionnier dans le Perfectionnement et le Coaching des Professionnels 
            de Santé 👨‍⚕  dans le domaine Médical 🩺 et Paramédical depuis 2018.
        </p>
        <div class="div-video">
            <iframe width="100%" height="315" src="https://www.youtube.com/embed/iTfnWmhmGa4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
        </div>
    </div>
</section>

formations/templates/conditions-generales-d-utilisation.html
{% extends "base.html" %}
{% block title %}AFIND Formation | {{ terms.title }}{% endblock %}
{% block content %}
<section class="formations section" id="formations">
    <h2 class="section-title">{{ terms.title }}</h2>
    <div class="container">
        {{ terms.content|safe }}
    </div>
</section>
{% endblock %}

formations/templates/contact.html
{% extends "base.html" %}
{% block title %}AFIND Formation{% endblock %}
{% block content %}
    <!--===== CONTACT =====-->
    {% include "contact_section.html" %}
{% endblock %}

formations/templates/contact_section.html
<section class="contact section" id="contact">
    <h2 class="section-title">Contactez <span class="subtitle">Nous</span></h2>
    <div class="container">
        <div class="contact-info">
            <h3>Informations de contact</h3>
            <p><i class="bx bx-phone"></i>(+213) 779 92 45 56</p>
            <p><i class="bx bx-envelope"></i>afindformation@gmail.com</p>
            <p><i class="bx bx-map"></i>Cité Ain Abdellah Coopérative, Résidence Rocher Noir 2, Bureau N°10, Boumerdes - ALGERIE</p>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3196.6555517044035!2d3.4510607765624575!3d36.75483811095225!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x128e68f78a47423d%3A0x1ccf933b681e8bdd!2sSIHHATECH!5e0!3m2!1sfr!2sdz!4v1715184587659!5m2!1sfr!2sdz" width="100%" height="350" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <form action="#" method="POST" class="contact-form">
            {% csrf_token %}
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {% if message.tags == 'success' %}
                        <i class='bx bx-check-circle alert-icon'></i>
                    {% elif message.tags == 'error' %}
                        <i class='bx bx-error-circle alert-icon'></i>
                    {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
            <label for="full_name">Nom:</label>
            <input type="text" id="full_name" name="full_name" placeholder="Votre nom" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" placeholder="Votre email" required>

            <label for="subject">Objet:</label>
            <input type="subject" id="subject" name="subject" placeholder="Votre objet" required>

            <label for="message">Message:</label>
            <textarea id="message" name="message" placeholder="Votre message" required></textarea>

            <button type="submit" class="button">Envoyer le message</button>
            
        </form>
    </div>
</section>

formations/templates/enroll_form.html
<form method="post" role="form" id="enrollForm">
    {% csrf_token %}
    <input type="text" id="id_full_name" name="full_name" placeholder="Nom et Prénom" required>
    <input type="email" id="id_email" name="email" placeholder="Email" required>
    <input type="tel" id="id_phone" name="phone" placeholder="téléphone" required>
    <input type="text" id="id_specialty" name="specialty"  placeholder="spécialité">
    <input type="text" id="id_region"  name="region" placeholder="Région">
    <!-- <button class="button  floating-btn" style="float: inline-end;"> S'inscrire </button> -->
</form>

formations/templates/faq.html
{% extends "base.html" %}
{% block title %}AFIND Formation | {{ faq.title }}{% endblock %}
{% block content %}
<section class="formations section" id="formations">
    <h2 class="section-title">{{ faq.title }}</h2>
    <div class="container">
        {{ faq.content|safe }}
    </div>
</section>
{% endblock %}

formations/templates/footer.html
{% load static %}
<footer class="footer">
    <hr>
    <div class="container">
        <div class="">
            <ul class="footer_list"> 
                <li><a href="/">Accueil</a></li>
                <li><a href="/a-propos">À propos</a></li>
                <li><a href="/formations">Formations</a></li>
            </ul>
        </div>
        <div class="">
            <h4>AIDE & SUPPORT</h4>
            <ul class="footer_list"> 
                <li><a href="/contact">Contact</a></li>
                <li><a href="/faq">FAQ</a>
            </ul>
        </div>
        <div class="footer_social">
            <a title="Logo" href="/" class="nav_logo">
                <img max-width="100%" height="auto" class="my-logo" id="my-logo" src="{% static 'img/Logo.png' %}" title="Logo" alt="AFIND">
                <!-- AFIND Formation  -->
            </a>
            <h4>SUIVEZ-NOUS</h4>
            <ul class="footer_list">
                <li><a target="_blank" href="https://www.facebook.com/AFINDFormation"><i class="bx bxl-facebook"></i></a></li>
                <li><a target="_blank" href="https://www.instagram.com/afindformation/"><i class="bx bxl-instagram"></i></a></li>
                <li><a target="_blank" href="https://www.linkedin.com/feed/update/urn:li:activity:7034534780243206144"><i class="bx bxl-linkedin"></i></a></li>
            </ul>
        </div>
    </div>
    <hr>
    <div>
        <div class="container">
            <p>Copyright &#169; 2024, tous droits réservés</p>
            <ul class="footer_ul"> 
                <li><a href="/politique-de-confidentialite">Politique de confidentialité |</a></li>
                <li><a href="/conditions-generales-d-utilisation">Conditions générales d’utilisation</a></li>
            </ul>
        </div>
    </div>
</footer>

formations/templates/formation_detail.html
{% extends "base.html" %}
{% block title %}AFIND Formation - {{ formation.title }}{% endblock %}
<!--===== MAIN =====-->
{% load static %}
{% block content %}
<!--===== FORMATION =====-->
<section class="formation section" id="">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {% if message.tags == 'success' %}
                        <i class='bx bx-check-circle alert-icon'></i>
                    {% elif message.tags == 'error' %}
                        <i class='bx bx-error-circle alert-icon'></i>
                    {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="desc_container">
            <div class="images-slider">
                <div class="imgSlides">
                    <img src="{{ formation.image.url }}" alt="{{ formation.title }}">
                </div>
                {% for img in formation_images %}
                    <div class="imgSlides">
                        <!-- <div class="numbertext">1 / 6</div> -->
                        <img src="{{ img.image.url }}" alt="{{ formation.title }}">
                    </div>
                {% endfor %}
                <!-- Next and previous buttons -->
                <a class="prev" onclick="plusSlides(-1)">&#10095;</a>
                <a class="next" onclick="plusSlides(1)">&#10094;</a>
                <!-- Thumbnail images -->
                <div class="row">
                    <div class="column">
                        <img class="demo cursor" src="{{ formation.image.url }}" alt="{{ formation.title }}" style="width:100%" onclick="currentSlide(1)">
                    </div>
                    {% for img in formation_images %}
                        <div class="column">
                            <img class="demo cursor" src="{{ img.image.url }}" alt="{{ formation.title }}" style="width:100%" onclick="currentSlide('{{ forloop.counter|add:1 }}')">
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="detial_container">
                <h3 class="title">{{ formation.title }}</h3>
                <!-- Promo Sign -->
                {% if formation.discount > 0 %}
                <span class="promo-sign">Promo</span>
                <p class="detail_label"><span class="discount">-{{ formation.discount }}%</span> <span class="discounted_price">{{ formation.discounted_price }}DA</span> <span class="detail_price">{{ formation.price }}DA</span></p>
                {% else %}
                <p class="detail_label"><span class="discounted_price" style="margin: auto;">{{ formation.price }}DA</span></p>
                {% endif %}
                <p class="detail_label">Durée :<span class=""> 10 mai - 15 mai 2024</span></p>
                <p class="detail_label">Instructeur :<span class=""> {{ formation.instructor }}</span></p>
                <p class="detail_label">Département :<span class=""> {{ formation.department }}</span></p>
                <p class="detail_label">Places restantes :<span class=""> Seulement {{ formation.places_left }} places restantes!</span></p>
                <p class="detail_label">Lieu :<span class=""> {{ formation.place }}</span> <span  style="float: right;">Date :<span class="detail_deadline"> {{ formation.date }}</span></span></p>
                <!--===== ENROLL FORM =====-->
                {% include "enroll_form.html" %}
            </div>
        </div>
        <br>
        <pre>{{ formation.description }}</pre>
        {% if formation.map_iframe %}
        <div class="map">
            {{ formation.map_iframe|safe }}
        </div>
        {% endif %}
        <!--===== MORE FORMATIONS =====-->
        {% include "formations_section.html" %}
        <button class="button floating-btn" onclick="submitEnrollForm()">s'inscrire</button>
    </div>
    <script>
        let slideIndex = 1;
        showSlides(slideIndex);
        
        // Next/previous controls
        function plusSlides(n) {
            showSlides(slideIndex += n);
        }
        
        // Thumbnail image controls
        function currentSlide(n) {
            showSlides(slideIndex = n);
        }
        
        function showSlides(n) {
            let i;
            let slides = document.getElementsByClassName("imgSlides");
            let dots = document.getElementsByClassName("demo");
            console.log(dots)
            console.log(slides)
            console.log(i, n)
            if (n > slides.length) {slideIndex = 1}
            if (n < 1) {slideIndex = slides.length}
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            console.log(i, slideIndex)
            slides[slideIndex-1].style.display = "block";
            dots[slideIndex-1].className += " active";
        }
    </script>
</section>
{% endblock %}

formations/templates/formations.html
{% extends "base.html" %}
{% block title %}AFIND Formation{% endblock %}
{% block content %}
{% load static %}
    <section class="home section" id="home">
        <!--===== SEARCH =====-->
        <section class="search" id="search">
            <div class="container">
                <form method="GET" action="{% url 'formations' %}">
                    <input type="text" name="q" placeholder="Rechercher des formations..." value="{{ request.GET.q }}">
                    <button class="button" type="submit">Rechercher</button>
                </form>
            </div>
        </section>
    </section>
    <!--===== FORMATIONS =====-->
    {% include "formations_section.html" %}
{% endblock %}

formations/templates/formations_section.html
<section class="formations section" id="formations">
    <h2 class="section-title">Nos <span class="subtitle">Formations</span></h2>
    <div class="container">
    {% if formations %}
    {% for formation in formations %}
        <article class="formations">
            <div class="formations-img">
                <a href="{% url 'formation' formation.id %}"><img src="{{ formation.image.url }}" alt="formation"></a>
            </div>
            <h4 class="subtitle">{{ formation.title }}</h4>
            {% if formation.discount > 0 %}
            <span class="promo-bar">Promo -{{ formation.discount }}%</span>
            {% endif %}
            <!-- 
            <p class="detail_label"><span class="discounted_price" style="margin: auto;">{{ formation.discounted_price }}DA</span> <span class="detail_price">{{ formation.price }}DA</span></p> 
            else 
            <p class="detail_label"><span class="discounted_price" style="margin: auto;">{{ formation.price }}DA</span></p>
            <p class="detail_label">Lieu :<span class=""> {{ formation.place }}</span> <span  style="float: right;">Date :<span class="detail_deadline"> {{ formation.date }}</span></span></p> 
            -->
            <p class="detail_label"><span  style="float: right;">Date :<span class="detail_deadline"> {{ formation.date }}</span></span></p>
            <a href="{% url 'formation' formation.id %}" class="button">plus de details <i class='bx bx-right-arrow-alt'></i></a>
        </article>
    {% endfor %}
    {% else %}
        <p>Aucune formation trouvée.</p>
    {% endif %}
</div>
</section>

formations/templates/header.html
{% load static %}
<header class="header" id="header">
    <nav class="nav">
        <a title="Logo" href="/" class="nav_logo">
            <img max-width="100%" height="auto" class="my-logo" id="my-logo" src="{% static 'img/Logo.png' %}" title="Logo" alt="AFIND">
            <!-- AFIND Formation  -->
        </a>
        <div class="nav_menu" id="nav-menu">
            <ul class="nav_list"> 
                <li class="nav_item"><a href="/" class="nav_link">Accueil</a></li>
                <li class="nav_item"><a href="/formations" class="nav_link">Formations</a></li>
                <li class="nav_item"><a href="/a-propos" class="nav_link">À propos</a></li>
                <li class="nav_item"><a href="/contact" class="nav_link">Contact</a></li>
            </ul>
        </div>
        <div class="nav_toggle">
            <i class="bx bx-menu" id="nav-toggle"></i>
        </div>
    </nav>
</header>

formations/templates/home.html
{% load static %}
<section class="home section" id="home">
    <div class="container">
        <h1 class="home_title">AFIND Formation, </h1>
        <h4>Centre de Coaching et de Perfectionnement dans le Médical destiné aux professionnels de la Santé</h4>
        <!-- <p class="text">Découvrez nos formations spécialisées pour professionnels de la santé.</p> -->
        <a href="/formations" class="button" style="margin: auto;">Explorez nos Formations</a>
    </div>
</section>

formations/templates/index.html
{% extends "base.html" %}
{% block title %}AFIND Formation{% endblock %}
{% block content %}
    <!--===== HOME =====-->
    {% include "home.html" %}
    <!--===== SEARCH =====-->
    <section class="search" id="search" style="padding: 2rem; background: #203039;">
        <div class="container">
            <form method="GET" action="{% url 'home' %}">
                <input type="text" name="q" placeholder="Rechercher des formations..." value="{{ request.GET.q }}">
                <button class="button" type="submit">Rechercher</button>
            </form>
        </div>
    </section>
    <!--===== FORMATIONS =====-->
    {% include "formations_section.html" %}
    <!--===== ABOUT =====-->
    {% include "about_section.html" %}
    <!--===== CONTACT =====-->
    {% include "contact_section.html" %}
{% endblock %}